spring.thymeleaf.cache=false
#logging.level.root=DEBUG
spring.groovy.template.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.groovy.template.GroovyTemplateAutoConfiguration
server.port=80